# Generated by Django 4.1 on 2022-09-07 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('loaded', models.BooleanField()),
                ('total_miles', models.FloatField()),
                ('finish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('gallons_fuel', models.DecimalField(decimal_places=4, max_digits=8)),
                ('fuel_date', models.DateTimeField(auto_now_add=True)),
                ('total_fuel_cost', models.DecimalField(decimal_places=3, max_digits=7)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckingfalconapi.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.ManyToManyField(to='truckingfalconapi.permissiontype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckingfalconapi.employee'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truckingfalconapi.truck'),
        ),
    ]
